ESTRUTURANDO DADOS COM NUMPY

In [ ]:
import numpy as np

#CRIANDO UM NUMPY ARRAY (NDARRAY)  (nao aceita elementos heterogeneos)
#CRIANDO UM NUMPY ARRAY 1-D
print(np.array([1,2,3]))

#CRIANDO UM NUMPY ARRAY 2-D
print(np.array([[1,2,3],[4,5,6]]))


[1 2 3]
[[1 2 3]
 [4 5 6]]


In [ ]:
#CRIANDO UMA MATRIZ NUMPY ARRAY
mtz = np.arange(1,101).reshape(10,10)
print(mtz)


[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [ ]:
print(mtz.max()) #maximo
print(mtz.min()) #minimo
print(mtz.mean())
print(mtz.size) #tamanho
print(mtz.shape) #shape

100
1
50.5
100
(10, 10)


In [ ]:
#OPERAÇÕES COM UM NUMPY ARRAY
arr1 = np.array([10,20,15]) #gastos com agua
arr2 = np.array([20,25,40]) #gastos com energia

#gastos total de cada mes
print(arr1+arr2)
#gastos total de tudo
print((arr1+arr2).sum())


[30 45 55]
130


In [ ]:
# TRABALHANDO COM NUMEROS ALEATORIOS
# RANDOM
np.random.seed(10) #semente aleatoria - permite gerar valores aleatorios iguais
mtz = np.random.randint(1,11,12).reshape(4,3)   #quero numeros de 1 - 10 gerando 12 numeros aleatorios  // reshape transforma em matriz
print(mtz)

#EXTRAINDO VALORES DAS COLUNAS DA MATRIZ
print(mtz.sum(axis=0))

#EXTRAINDO VALORES DAS LINHAS DA MATRIZ
print(mtz.sum(axis=1))

#EXTRAINDO O VALOR DE GASTOS COM NET
print(mtz.sum(axis=1)[2])

[[10  5  1]
 [ 2 10  1]
 [ 2  9 10]
 [ 1  9  7]]
[15 33 19]
[16 13 21 17]
21


In [9]:
#EXTRAIR ELEMENTOS UNICOS
print(np.unique(mtz))
#agora faz contagem de quantos elementos tem naquela matriz
print(np.unique(mtz,return_counts=True))

[ 1  2  5  7  9 10]
(array([ 1,  2,  5,  7,  9, 10]), array([3, 2, 1, 1, 2, 3]))
